version: '3'

tasks:
  lint:
    desc: Lint code using ruff
    cmds:
      - uv run ruff check . --fix

  format:
    desc: Format code using ruff
    cmds:
      - uv run ruff format .

  serve:
    desc: Start the Analytics Dashboard
    aliases: 
      - dev
    cmds:
      - uv run python -m src.main

  test:
    desc: Run tests
    cmds:
      - echo "No tests implemented yet"
